version: '3'

networks:
  test_kube_default:


services:

  banking-mysql:
    image: bdfb0ec4d54ad6c6f51e03ce444f792731ac97d79c4575ee74e291b01b6a4bed
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    networks:
      - test_kube_default

  jenkins-test-1-mysql:
    image: 8001dabf7e43d700c178c77399c23cf549b4b9bc6d8f35e9946dfbac45021f62
    ports:
      - "8090:8090"
    depends_on:
      - banking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    networks:
      - test_kube_default
