def  GIT_BRANCH = 'main'
def  GIT_REPOSITORY_URL = 'https://github.com/gamepkw/jenkins-test-1.git'
def  APP_NAME = 'go-app'
def  APP_VERSION = 'latest'
def  IMAGE_REPOSITORY = 'docker.io/gamepkw/jenkins-test-1'

def  NAMESPACE_NAME = 'jenkins-test-1-namespace'
def  DEPLOYMENT_NAME = 'jenkins-test-1-deployment'
def  SERVICE_NAME = 'jenkins-test-1-nodeport-service'

pipeline {
    agent any

    tools {
        go 'go'
        dockerTool 'docker'
    }

    environment {
        KUBE_CONFIG = "/var/snap/microk8s/current/credentials/client.config"
    }

    stages {

        stage('Clean') {
            steps {
                script {
                    cleanWs()
                    sh "docker images --format '{{.Repository}}:{{.Tag}}' | grep '^${APP_NAME}' | xargs -I {} docker rmi -f {}"
                    sh "docker images --format '{{.Repository}}:{{.Tag}}' | grep '^${IMAGE_REPOSITORY}' | xargs -I {} docker rmi -f {}"
                    def unusedImages = sh(script: 'docker images | grep "<none>" | awk \'{print $3}\'', returnStdout: true).trim()
                    if (unusedImages) {
                        def imageIds = unusedImages.split()
                        imageIds.each { imageId ->
                            sh "docker rmi -f $imageId"
                        }
                    } else {
                        echo "No images with '<none>' tag found."
                    }
                }
            }
        }
        stage('Git Pull') {
            steps {
                script {
                    git branch: "${GIT_BRANCH}", url: "${GIT_REPOSITORY_URL}"
                    try {
                        appVersion = sh(returnStdout: true, script: 'git tag --contains | tail -1 | grep -E "^[0-9]+\\.[0-9]+\\.[0-9]+$"').trim()
                        if (appVersion) {
                            APP_VERSION = appVersion
                        }
                    } catch (Exception e) {
                        echo "No valid version tag found. Using default version."
                    }
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh "go mod tidy"
                }
            }
        }
        stage('Docker Authentication') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-secret', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                    }
                }
            }
        }
        stage('Build Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_REPOSITORY}:${APP_VERSION} ."
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                    def imageId = sh(script: "docker images -q ${IMAGE_REPOSITORY}:${APP_VERSION}", returnStdout: true).trim()
                    sh "docker push ${IMAGE_REPOSITORY}:${APP_VERSION}"
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def namespaceExists = sh(script: "kubectl get namespace ${NAMESPACE_NAME} --kubeconfig=${KUBE_CONFIG}", returnStatus: true) == 0

                    if (!namespaceExists) {
                        sh script: "kubectl create namespace ${NAMESPACE_NAME} --kubeconfig=${KUBE_CONFIG}", returnStatus: true
                        echo "Namespace ${NAMESPACE_NAME} created or updated successfully."
                    } else {
                        echo "Namespace ${NAMESPACE_NAME} already exists."
                    }

                    sh "kubectl apply -f deployment.yaml -n ${NAMESPACE_NAME} --kubeconfig=${KUBE_CONFIG}"

                    sh "kubectl apply -f nodeport-service.yaml -n ${NAMESPACE_NAME} --kubeconfig=${KUBE_CONFIG}"
                }
            }
        }
    }
}