apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-1-deployment
  namespace: jenkins-test-1-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-test-1-app
  template:
    metadata:
      labels:
        app: jenkins-test-1
    spec:
      containers:
        - name: jenkins-test-1-container
          image: docker.io/gamepkw/jenkins-test-1-image:latest
          ports:
            - containerPort: 8090
