apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-1-nodeport-service
  namespace: jenkins-test-1-namespace
spec:
  type: NodePort
  selector:
    app: jenkins-test-1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30001
