apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: jenkins-test-1-pods
      image: gamepkw/jenkins-test-1-pods-image:latest
      ports:
        - containerPort: 8090
